### ISSUE TITLE
New opportunity ?

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [aurelg/feedspora#1]
Hey buddy, 

I happened to find your repository after the issue you created here: https://github.com/DEKHTIARJonathan/python3-linkedin/issues/5

It seems like we share a lot of common goals, so I will allow myself to bring your attention to a project of mine which has common features with yours: https://github.com/DEKHTIARJonathan/FeedCrunch.IO

The website is available here: https://www.feedcrunch.io/
And my personal page: https://www.feedcrunch.io/@dataradar/

The core concepts we share:
- a unified platform to handle RSS Feeds
- automatically repost on various social networks entries of an RSS Feed
  - LinkedIn
  - Facebook
  - Twitter
  - Slack
  - more comming

I invite you to read the readme of the project: https://github.com/DEKHTIARJonathan/FeedCrunch.IO

Maybe you would be open to some discussion and we could find a way to work together ? You tell me.

**Comment by aurelg** [comment]
Hi!

It indeed seems we have some shared interests! Feedspora is an old project of mine, but it (still) works well. Since then, I'm [playing with links collection and ranking](https://latitude77.org/veille) - in French, but I guess that won't be a problem.

FeedCrunch looks promising and is already rather polished. I like the idea very much. I'm wide open to discussions. Maybe you already have something in mind ? FWIW, since I'm not a professional developer, I usually tackle complexity by hacking KISS tools following the UNIX motto 'Write programs that do one thing and do it well', then use them in powerful combos. But, well, UI/UX... ^^
