### ISSUE TITLE
The order of hashtags / keywords should reflect the order of the categories in the parent feed

### ISSUE THREAD

**Issue by aurelg** [aurelg/feedspora#16]
The current implementation filters out duplicated categories by converting the list of categories into a `set` in the [Atom](https://github.com/aurelg/feedspora/blob/master/src/feedspora/feedspora_runner.py#L466) and [RSS](https://github.com/aurelg/feedspora/blob/master/src/feedspora/feedspora_runner.py#L486) parsers.

The order of categories is not defined in the [Atom](https://tools.ietf.org/html/rfc4287) and [RSS](http://www.rssboard.org/rss-specification) specifications. We can't assume that the order is relevant or not and it makes sense not to alter it.

**Comment by wilddeej** [comment]
I was going to take this one on, but I wanted to consult with you before I did.  Here's what I'm thinking:

We already agreed to use a list implementation consistently, to preserve order.  As far as that ordering and the priority of keywords, this is what I propose:
1. Keywords found in the title (since this is the "main" part of any posting, and so any tags it contains should have highest priority),
2. Keywords found within the content of the posting,
3. Keywords from the category of the posting,
These would be implemented within the feed parsers, of course.

Some of this functionality is currently implemented (or partially implemented) within the various clients, so there may be some client-specific changes needed as well, but they should functionally remain the same as they are now.
You've already mentioned that you want the clients to behave as consistently as possible (and I agree).  That will mean that we will need to come up with a strategy for how the keywords from the feed parsers will be treated in conjunction with the optional client-specific keywords list (from the YAML file) and the setting of the max_tags parameter.  I think that the user specification should take precedence over the feed-generated keywords list (so, pushed on to the front of the list, in the order specified by the user), and then max_tags is applied to limit that full list.

What do you think?
